title: Services
template: templates/interior
layout: layout
mount: 5add62ea-f5e1-41ba-8c9d-2e4107c5866a
revisions: false
route: '{mount}/{slug}'
sort_dir: desc
date_behavior:
  past: public
  future: private
preview_targets:
  -
    label: Entry
    url: '{permalink}'
    refresh: true
structure:
  root: false
  max_depth: 1
