tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: content
            field:
              type: markdown
              localizable: true
      -
        display: Preview
        fields:
          -
            handle: preview_title
            field:
              input_type: text
              antlers: false
              type: text
              display: 'Preview Title'
              instructions: "Short version of this entry's title that services as an id."
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            import: preview
            prefix: preview_
  seo:
    display: SEO
    sections:
      -
        display: SEO
        fields:
          -
            import: 'statamic-peak-seo::seo_basic'
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
          -
            handle: parent
            field:
              type: entries
              collections:
                - services
              max_items: 1
              listable: false
              localizable: true
title: Service
