tabs:
  main:
    display: Main
    sections:
      -
        display: Core
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: content
            field:
              type: markdown
              localizable: true
          -
            handle: featured_image
            field:
              max_files: 1
              mode: list
              container: images
              restrict: false
              allow_uploads: true
              show_filename: true
              show_set_alt: true
              type: assets
              display: 'Featured Image'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: woocommerce_product_id
            field:
              type: integer
              display: 'WooCommerce Product Id'
              instructions: 'The four-digit product id in the WooCommerce database, to look up format types.'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
      -
        display: Preview
        fields:
          -
            handle: preview_title
            field:
              input_type: text
              antlers: false
              type: text
              display: 'Preview Title'
              instructions: "Short version of this entry's title that services as an id."
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            import: preview
            prefix: preview_
      -
        display: Features
        fields:
          -
            handle: features
            field:
              collapse: false
              previews: true
              fullscreen: true
              sets:
                new_set_group:
                  display: 'New Set Group'
                  instructions: null
                  icon: null
                  sets:
                    new_feature:
                      display: 'New Feature'
                      instructions: null
                      icon: null
                      fields:
                        -
                          import: feature
              type: replicator
              display: Features
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
      -
        display: Formats
        fields:
          -
            handle: formats_heading_highlight
            field: common.heading_highlight
          -
            handle: formats_text_description
            field: common.text_description
      -
        display: FAQs
        fields:
          -
            handle: faqs
            field:
              collapse: false
              previews: true
              fullscreen: true
              sets:
                new_set_group:
                  display: 'New Set Group'
                  instructions: null
                  icon: null
                  sets:
                    new_faq:
                      display: 'New FAQ'
                      instructions: null
                      icon: null
                      fields:
                        -
                          import: faq
                          prefix: faq_
              type: replicator
              display: FAQs
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
  seo:
    display: SEO
    sections:
      -
        display: SEO
        fields:
          -
            import: 'statamic-peak-seo::seo_basic'
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
          -
            handle: parent
            field:
              type: entries
              collections:
                - services
              max_items: 1
              listable: false
              localizable: true
title: Service
